name: Deploy book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8'
          cabal-version: '3.10.2.1'

      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Install SVGO
        run: npm install -g svgo

      - name: Checkout
        uses: actions/checkout@v6

      - name: Process illustrations
        run: |
          outputDirectory="public/img"
          for file in book/illustrations/*; do
              if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  echo "Processing file: $filename"
                  inkscape --file="$file" --export-text-to-path -o "$outputDirectory"/"$filename"
                  svgo -i "$outputDirectory"/"$filename" --final-newline --multipass
              fi
          done

      - name: Compile book
        run: |
          cd compiler
          cabal v2-run haskellBook.cabal -- "../book/" "../public/"

      - name: Upload site
        uses: actions/upload-artifact@v7
        with:
          name: site
          path: public/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@v8
        with:
          name: site
          path: public

      - name: Prepare SCP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
          sudo chmod 600 ~/.ssh/key
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H new.ubavic.rs >> ~/.ssh/known_hosts

      - name: Publish via SCP
        run: scp -P ${{ secrets.SSH_PORT }} -i ~/.ssh/key -r public/* ${{ secrets.USER }}@new.ubavic.rs:/var/www/haskel.ubavic.rs
